openapi: 3.0.0
info:
  title: Client API
  version: '1.0'
  description: ''
servers:
  - url: 'https://api.ostravar.cz/api'
paths:
  /auth/login:
    post:
      summary: ''
      operationId: post-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: object
                    properties:
                      accessToken:
                        type: string
                      refreshToken:
                        type: string
                      userId:
                        type: number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
    parameters: []
  /auth/logout:
    post:
      summary: ''
      operationId: post-api-auth-logout
      responses:
        '200':
          description: OK
    parameters: []
  /auth/user:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-api-auth-user
    parameters: []
  /auth/refresh:
    post:
      summary: ''
      operationId: post-api-auth-refresh
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: object
                    properties:
                      accessToken:
                        type: string
                      refreshToken:
                        type: string
    parameters: []
components:
  schemas: {}
